#include <unity_fixture.h>
#include <j3dcore/j3d.h>

#if defined(J3D_DIRECTX6)

#include <stddef.h>

#include <std/General/stdUtil.h>
#include <std/Win95/stdControl.h>
#include <std/Win95/std3D.h>

TEST_GROUP(stdWin95DirectX6);

TEST_SETUP(stdWin95DirectX6)
{}

TEST_TEAR_DOWN(stdWin95DirectX6)
{}

TEST(stdWin95DirectX6, TestDirectInputMouseJoystickStateLayout)
{
    TEST_ASSERT_EQUAL_size_t(4u, STD_ARRAYLEN(((DIMOUSESTATE*)0)->rgbButtons));
    TEST_ASSERT_EQUAL_size_t(4u, STD_ARRAYLEN(((DIJOYSTATE*)0)->rgdwPOV));
    TEST_ASSERT_EQUAL_size_t(32u, STD_ARRAYLEN(((DIJOYSTATE*)0)->rgbButtons));
    TEST_ASSERT_EQUAL_size_t(4u, STD_ARRAYLEN(((DIJOYSTATE2*)0)->rgdwPOV));
    TEST_ASSERT_EQUAL_size_t(128u, STD_ARRAYLEN(((DIJOYSTATE2*)0)->rgbButtons));

    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, lX), DIMOFS_X);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, lY), DIMOFS_Y);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, lZ), DIMOFS_Z);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, rgbButtons) + 0u, DIMOFS_BUTTON0);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, rgbButtons) + 3u, DIMOFS_BUTTON3);
}

TEST(stdWin95DirectX6, TestDirectInputJoystickOffsetsMatchStdControlLayout)
{
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lX), DIJOFS_X);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lY), DIJOFS_Y);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lZ), DIJOFS_Z);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lRx), DIJOFS_RX);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lRy), DIJOFS_RY);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lRz), DIJOFS_RZ);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgdwPOV), DIJOFS_POV(0));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgdwPOV) + sizeof(DWORD) * 3u, DIJOFS_POV(3));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgbButtons), DIJOFS_BUTTON(0));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgbButtons) + 31u, DIJOFS_BUTTON(31));

    TEST_ASSERT_EQUAL_UINT32(100u, DI_DEGREES);
    TEST_ASSERT_EQUAL_UINT32(0u, STDCONTROL_MAX_GAMEPAD_DEVICES);
    TEST_ASSERT_EQUAL_UINT32(8u, STDCONTROL_MAX_JOYSTICK_DEVICES);
    TEST_ASSERT_EQUAL_UINT32(48u, STDCONTROL_MAX_JOYSTICK_AXES);
    TEST_ASSERT_EQUAL_UINT32(644u, STDCONTROL_MAX_KEYID);
    TEST_ASSERT_EQUAL_UINT32(640u, STDCONTROL_KID_MOUSE_LBUTTON);
    TEST_ASSERT_EQUAL_UINT32(643u, STDCONTROL_KID_MOUSE_XBUTTON);
}

TEST(stdWin95DirectX6, TestDirect3D6StdTypeAliasesAndFixedFunctionVertexFormat)
{
    TEST_ASSERT_EQUAL_size_t(sizeof(DDPIXELFORMAT), sizeof(tSysPixelFormat));
    TEST_ASSERT_EQUAL_size_t(sizeof(DDSURFACEDESC2), sizeof(tSysSurfaceDesc));
    TEST_ASSERT_EQUAL_size_t(sizeof(D3DDEVICEDESC), sizeof(tSysDevice3DDesc));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)(D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_SPECULAR | D3DFVF_TEX1), D3DFVF_TLVERTEX);
    TEST_ASSERT_EQUAL_size_t(sizeof(D3DTLVERTEX), sizeof(*((LPD3DTLVERTEX)0)));
    TEST_ASSERT_EQUAL_UINT32(64u, STD3D_MAXFACEVERTICES);
    TEST_ASSERT_EQUAL_UINT32(32768u, STD3D_MAXVERTICES);
}

TEST_GROUP_RUNNER(stdWin95DirectX6)
{
    RUN_TEST_CASE(stdWin95DirectX6, TestDirectInputMouseJoystickStateLayout);
    RUN_TEST_CASE(stdWin95DirectX6, TestDirectInputJoystickOffsetsMatchStdControlLayout);
    RUN_TEST_CASE(stdWin95DirectX6, TestDirect3D6StdTypeAliasesAndFixedFunctionVertexFormat);
}

#endif
