#include <unity_fixture.h>
#include <j3dcore/j3d.h>

#if defined(J3D_DIRECTX9)

#include <stddef.h>

#include <std/General/stdUtil.h>
#include <std/Win95/DX9/stdShaderDX9.h>
#include <std/Win95/stdControl.h>

TEST_GROUP(stdWin95DirectX9);

TEST_SETUP(stdWin95DirectX9)
{}

TEST_TEAR_DOWN(stdWin95DirectX9)
{}

TEST(stdWin95DirectX9, TestDirectInputVersionAndMouseJoystickStateLayout)
{
    TEST_ASSERT_EQUAL_UINT32(0x0800u, DIRECTINPUT_VERSION);
    TEST_ASSERT_EQUAL_size_t(4u, STD_ARRAYLEN(((DIJOYSTATE*)0)->rgdwPOV));
    TEST_ASSERT_EQUAL_size_t(32u, STD_ARRAYLEN(((DIJOYSTATE*)0)->rgbButtons));
    TEST_ASSERT_EQUAL_size_t(4u, STD_ARRAYLEN(((DIJOYSTATE2*)0)->rgdwPOV));
    TEST_ASSERT_EQUAL_size_t(128u, STD_ARRAYLEN(((DIJOYSTATE2*)0)->rgbButtons));
    TEST_ASSERT_EQUAL_size_t(8u, STD_ARRAYLEN(((DIMOUSESTATE2*)0)->rgbButtons));

    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, lX), DIMOFS_X);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, lY), DIMOFS_Y);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, lZ), DIMOFS_Z);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, rgbButtons) + 0u, DIMOFS_BUTTON0);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE, rgbButtons) + 3u, DIMOFS_BUTTON3);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE2, rgbButtons) + 4u, DIMOFS_BUTTON4);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIMOUSESTATE2, rgbButtons) + 7u, DIMOFS_BUTTON7);
}

TEST(stdWin95DirectX9, TestDirectInputJoystickOffsetsMatchStdControlLayout)
{
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lX), DIJOFS_X);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lY), DIJOFS_Y);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lZ), DIJOFS_Z);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lRx), DIJOFS_RX);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lRy), DIJOFS_RY);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, lRz), DIJOFS_RZ);
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgdwPOV), DIJOFS_POV(0));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgdwPOV) + sizeof(DWORD) * 3u, DIJOFS_POV(3));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgbButtons), DIJOFS_BUTTON(0));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)FIELD_OFFSET(DIJOYSTATE, rgbButtons) + 31u, DIJOFS_BUTTON(31));

    TEST_ASSERT_EQUAL_UINT32(100u, DI_DEGREES);
    TEST_ASSERT_EQUAL_UINT32(4u, STDCONTROL_MAX_GAMEPAD_DEVICES);
    TEST_ASSERT_EQUAL_UINT32(12u, STDCONTROL_MAX_JOYSTICK_DEVICES);
    TEST_ASSERT_EQUAL_UINT32(72u, STDCONTROL_MAX_JOYSTICK_AXES);
    TEST_ASSERT_EQUAL_UINT32(836u, STDCONTROL_MAX_KEYID);
    TEST_ASSERT_EQUAL_UINT32(832u, STDCONTROL_KID_MOUSE_LBUTTON);
    TEST_ASSERT_EQUAL_UINT32(835u, STDCONTROL_KID_MOUSE_XBUTTON);
}

TEST(stdWin95DirectX9, TestDirect3D9StdTypeAliasesAndShaderConstants)
{
    // Verify the public DirectX type aliases and vertex declaration values.
    TEST_ASSERT_EQUAL_size_t(sizeof(D3DFORMAT), sizeof(tSysPixelFormat));
    TEST_ASSERT_EQUAL_size_t(sizeof(D3DSURFACE_DESC), sizeof(tSysSurfaceDesc));
    TEST_ASSERT_EQUAL_size_t(sizeof(D3DCAPS9), sizeof(tSysDevice3DDesc));
    TEST_ASSERT_EQUAL_UINT32((uint32_t)(D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_SPECULAR | D3DFVF_TEX1), D3DTLVERTEX_FVF);
    TEST_ASSERT_EQUAL_INT(3, D3DDECLTYPE_FLOAT4);
    TEST_ASSERT_EQUAL_INT(4, D3DDECLTYPE_D3DCOLOR);
    TEST_ASSERT_EQUAL_INT(1, D3DDECLTYPE_FLOAT2);

    // Shader capacities and register offsets must remain compatible with the shared vertex format.
    TEST_ASSERT_EQUAL_UINT32(64u, STDSHADERDX9_MAX_SHADERS);
    TEST_ASSERT_EQUAL_UINT32(24u, STDSHADERDX9_VS_CONSTANTS_START_REGISTER);
    TEST_ASSERT_EQUAL_UINT32(8u, STDSHADERDX9_PS_CONSTANTS_START_REGISTER);
    TEST_ASSERT_EQUAL_UINT32(216u, STDSHADERDX9_MAX_PS_PARAMS);
    TEST_ASSERT_EQUAL_size_t(0u, offsetof(StdShaderDX9, base));
}

TEST_GROUP_RUNNER(stdWin95DirectX9)
{
    RUN_TEST_CASE(stdWin95DirectX9, TestDirectInputVersionAndMouseJoystickStateLayout);
    RUN_TEST_CASE(stdWin95DirectX9, TestDirectInputJoystickOffsetsMatchStdControlLayout);
    RUN_TEST_CASE(stdWin95DirectX9, TestDirect3D9StdTypeAliasesAndShaderConstants);
}

#endif
